### ISSUE TITLE
does not parse smarthost port number

### ISSUE THREAD

**Issue by GregorZattler** [xundeenergie/exim4-multiaccount#2] opened 2017-05-28 20:50 UTC
from my /var/log/exim4/mainlog:

2017-05-28 22:30:43 1dF4pm-0001my-LK == x.yyyyyyy@zzz.de R=smarthost_multiaccount T=remote_smtp_smarthost_multiaccount defer (-1): TCP port "" is not defined for remote_smtp_smarthost_multiaccount transport 

seems to show that the port number provided in the 4th field of client.multismarthost_multiaccount.passwd  is not parsed correctly.

Thanks for providing your package which would solve a long standing problem for me.

**Comment by xundeenergie** [comment] 2017-05-28 23:44
Hi!
First thank you for reporting this issue.

I think i fixed this now. If the port-field was empty, it was set to port 25. If it was not empty, port was set to ""... now it should be set to the correct port.

Please test it, and I would be glad, if you can report, if the issue is fixed for you.

**Comment by GregorZattler** [comment] 2017-05-29 12:47
Yes, it seems to work now with version 1.40 (version s37-39 I did not test)!  I configured port 587 and the mainlog talks about TLS 1.2 which I consider a good sign.

Thank you so much, I wanted this for years!

**Comment by xundeenergie** [comment] 2017-06-01 07:53
Thanks for reply!
I think, i can close this issue. It works for me too. Checked it in debug-mode, and all seems to use the correct ports.

And yes... i was looking also for many years for that feature, wondering, why it is not in standardconfiguration :)

And exim-configs are really not easy to understand or write them self.

**Closed as completed** 2017-06-01 07:53 UTC
